name: CI/CD and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint code
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Build project
      run: npm run build
      
    - name: Determine CDN URLs
      id: cdn
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          # Tag push - use npm version
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}  # Remove 'v' prefix if present
          URL="https://cdn.jsdelivr.net/npm/bootstrap-italia-wc@${VERSION}/dist/bootstrap-italia-wc.js"
          URL_MIN="https://cdn.jsdelivr.net/npm/bootstrap-italia-wc@${VERSION}/dist/bootstrap-italia-wc.min.js"
          URL_ESM="https://cdn.jsdelivr.net/npm/bootstrap-italia-wc@${VERSION}/dist/bootstrap-italia-wc.esm.js"
        else
          # Master branch - use latest branch
          URL="https://cdn.jsdelivr.net/gh/blacksoulgem95/bootstrap-italia-wc@latest/bootstrap-italia-wc.js"
          URL_MIN="https://cdn.jsdelivr.net/gh/blacksoulgem95/bootstrap-italia-wc@latest/bootstrap-italia-wc.min.js"
          URL_ESM="https://cdn.jsdelivr.net/gh/blacksoulgem95/bootstrap-italia-wc@latest/bootstrap-italia-wc.esm.js"
        fi
        
        echo "url=${URL}" >> $GITHUB_OUTPUT
        echo "url_min=${URL_MIN}" >> $GITHUB_OUTPUT
        echo "url_esm=${URL_ESM}" >> $GITHUB_OUTPUT
      
    - name: Prepare documentation
      run: |
        # Copy examples to docs for GitHub Pages
        mkdir -p docs
        cp -r examples/* docs/
        
        # Update all HTML files to use CDN links
        find docs -name "*.html" -type f | while read file; do
          # Replace local script references with CDN
          sed -i "s|src=\"\.\./dist/bootstrap-italia-wc\.js\"|src=\"${{ steps.cdn.outputs.url }}\"|g" "$file"
          sed -i "s|src=\"dist/bootstrap-italia-wc\.js\"|src=\"${{ steps.cdn.outputs.url }}\"|g" "$file"
          sed -i "s|src=\"\.\./dist/bootstrap-italia-wc\.min\.js\"|src=\"${{ steps.cdn.outputs.url_min }}\"|g" "$file"
          sed -i "s|src=\"dist/bootstrap-italia-wc\.min\.js\"|src=\"${{ steps.cdn.outputs.url_min }}\"|g" "$file"
          sed -i "s|src=\"\.\./dist/bootstrap-italia-wc\.esm\.js\"|src=\"${{ steps.cdn.outputs.url_esm }}\"|g" "$file"
          sed -i "s|src=\"dist/bootstrap-italia-wc\.esm\.js\"|src=\"${{ steps.cdn.outputs.url_esm }}\"|g" "$file"
        done
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        destination_dir: .
        exclude_assets: ''