name: Update Latest Branch

on:
  push:
    branches:
      - master

jobs:
  update-latest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build package
        run: npm run build
        
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Checkout or create latest branch
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/latest; then
            git checkout latest
            git pull origin latest
          else
            git checkout -b latest
          fi
          
      - name: Copy dist files to latest branch
        run: |
          # Copy dist files
          cp -r dist/* .
          
          # Create package.json for latest branch
          cat > package.json << EOF
          {
            "name": "bootstrap-italia-wc-latest",
            "version": "latest",
            "description": "Bootstrap Italia Web Components - Latest Build",
            "main": "bootstrap-italia-wc.js",
            "files": [
              "bootstrap-italia-wc.js",
              "bootstrap-italia-wc.min.js",
              "bootstrap-italia-wc.esm.js"
            ],
            "repository": {
              "type": "git",
              "url": "https://github.com/${{ github.repository }}.git",
              "directory": "latest"
            },
            "keywords": [
              "bootstrap-italia",
              "web-components",
              "ui-components",
              "accessibility"
            ],
            "author": "Bootstrap Italia WC Team",
            "license": "MIT"
          }
          EOF
          
          # Create README for latest branch
          cat > README.md << EOF
          # Bootstrap Italia WC - Latest Build
          
          This is the latest build of Bootstrap Italia Web Components.
          
          ## Usage
          
          \`\`\`html
          <!-- CSS -->
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-italia@2.0.0/dist/css/bootstrap-italia.min.css">
          
          <!-- JavaScript -->
          <script src="https://cdn.jsdelivr.net/gh/blacksoulgem95/bootstrap-italia-wc@latest/bootstrap-italia-wc.js"></script>
          \`\`\`
          
          ## Files
          
          - \`bootstrap-italia-wc.js\` - Development build
          - \`bootstrap-italia-wc.min.js\` - Production build (minified)
          - \`bootstrap-italia-wc.esm.js\` - ES Module build
          
          ## Version
          
          Latest build from commit: \`${{ github.sha }}\`
          
          Built on: \`$(date -u +"%Y-%m-%d %H:%M:%S UTC")\`
          EOF
          
      - name: Commit and push to latest branch
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update latest build from master (${{ github.sha }})"
            git push origin latest
          fi